{
 "title": "IT Optimization with IBM LinuxONE",
 "description": "Show IT Optimization when moving workloads from x86 to LinuxONE",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Application Performance Metrics</h1>"
   }
  },
  {
   "title": "x86 Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IBM LinuxONE Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "SELECT mean(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "x86 Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Requests per Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IBM LinuxONE Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "Requests per Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "x86 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IBM LinuxONE Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "x86 Average Requests per Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "x86 Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "IBM LinuxONE Average Requests per Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 111 }
   ]
  },
  {
   "title": "IBM LinuxONE Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 112 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Application Environmental Metrics</h1>"
   }
  },
  {
   "title": "x86 Power Consumption (Max)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{id=\"103\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_power_watts{name=\"Avg Power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy saving from x86 to IBM LinuxONE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{id=\"103\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_power_watts{name=\"Avg Power\"}",
     "legendFormat": "__auto"
    },
    {
     "query": "SELECT mean(\"total-infrastructure-power-consumption\") FROM \"Energy Data\" WHERE $timeFilter AND  \"cpc\" = 'MENSA' GROUP BY time($__interval) fill(none)"
    },
    {
     "query": "SELECT mean(\"power-consumption\") FROM \"LPAR Metrics\" WHERE $timeFilter AND \"cpc\" = 'MENSA' AND \"lpar\" = 'MENSA03' GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "IBM LinuxONE Power Consumption (Max)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"power-consumption\") FROM \"LPAR Metrics\" WHERE $timeFilter AND \"cpc\" = 'MENSA' AND \"lpar\" = 'MENSA03' GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "x86 Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "IBM LinuxONE Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 63 }
   ]
  },
  {
   "title": "6 X86 Servers",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
   "options": {
    "content": "<div style=\"display: flex; flex-wrap: wrap; justify-content: center; gap: 10px;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n  <img src=\"https://raw.githubusercontent.com/mmondics/media/refs/heads/main/images/sr650.png\" style=\"max-width: 30%; height: auto;\">\n</div>\n"
   }
  },
  {
   "title": "1  IBM LinuxONE LPAR",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
   "options": {
    "content": "<img src=\"https://www.ibm.com/demos/it-infrastructure/IBM_LinuxONE_Emperor4/img/linux_ONE_isolated.png\" style=\"max-width: 100%; max-height: 100%; width: auto; height: auto; display: block; margin: auto;\">"
   }
  },
  {
   "title": "x86 Carbon Emissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "IBM LinuxONE Carbon Emissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 63 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Infrastructure Monitoring Metrics</h1>"
   }
  },
  {
   "title": "x86 Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "IBM LinuxONE Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "panelId": 63 }
   ]
  },
  {
   "title": "x86 Red Hat OpenShift Cluster",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 44 },
   "options": {
    "content": "<br>\n<h2><center><p style=\"color: gray;\">VMware vSphere (RHEL 9 VMware ESXi)</p></center></h2>"
   },
   "targets": [
    {
     "expr": "zhmc_partition_description{cpc=\"INDUS\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IBM LinuxONE Red Hat OpenShift Cluster",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 44 },
   "options": {
    "content": "<br>\n<h2><center><p style=\"color: orange;\">KVM (RHEL 9 KVM)</p></center></h2>"
   },
   "targets": [
    {
     "expr": "zhmc_partition_description{cpc=\"INDUS\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total x86 CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.181\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrDeviceType{instance=\"10.11.0.182\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrDeviceType{instance=\"10.11.0.183\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrDeviceType{instance=\"10.11.0.184\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrDeviceType{instance=\"10.11.0.185\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrDeviceType{instance=\"10.11.0.186\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consolidation Factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zhmc_partition_ifl_processor_count{cpc=\"MENSA\", partition=\"MENSA03\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IBM LinuxONE Cores (IFLs)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zhmc_partition_ifl_processor_count{cpc=\"MENSA\", partition=\"MENSA03\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR650",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.181\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR650",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.182\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR650",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.183\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR650",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.184\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR650",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.184\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "x3650 M5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceType{instance=\"10.11.0.185\", hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IBM LinuxONE 5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 42 }
   ]
  },
  {
   "title": "CPU Utilization - x86",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ipmi_sensor_value{id=\"99\", name=\"CPU Utilization\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_sensor_value{id=\"7\", name=\"CPU Utilization\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - IBM LinuxONE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT \"processor-usage\" FROM \"LPAR Metrics\" WHERE $timeFilter AND \"cpc\" = 'MENSA' AND \"lpar\" = 'MENSA03'"
    }
   ]
  }
 ]
}